/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-08-29 11:50:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/kimseula/Desktop/kimseula/_1_Project/BucketClass_PAP/project/bucketclass/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bucketclass/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1482307844000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.1.RELEASE.jar", Long.valueOf(1566828078816L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!-- Basic Page Needs -->\r\n");
      out.write("<title>BucketClass</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/main-color.css\" id=\"colors\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"../img/favicon-32x32.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Wrapper -->\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("<!-- Header Container -->\r\n");
      out.write("<header id=\"header-container\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Left Side Content -->\r\n");
      out.write("\t\t\t<div class=\"left-side\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"main.html\"><img src=\"../img/logo.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t<!-- Main Navigation / End -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Left Side Content / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Right Side Content  -->\r\n");
      out.write("            <div class=\"right-side\">\r\n");
      out.write("                <div class=\"header-widget\">\r\n");
      out.write("                       ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                       ");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Right Side Content / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Header / End -->\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("<!-- Header Container / End -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Banner -->\r\n");
      out.write("\t<div class=\"main-search-container\" data-background-image=\"../img/main-study.jpg\">\r\n");
      out.write("\t\t<div class=\"main-search-inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<h2>가까운 지역의 수업을 찾아보세요!</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main-search-input\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-search-input-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"어떤 수업을 찾으시나요?\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-search-input-item location\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"autocomplete-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"autocomplete-input\" type=\"text\" placeholder=\"지역을 선택하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-map-marker\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"main-search-input-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select data-placeholder=\"All Categories\" class=\"chosen-select\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>모든 카테고리</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>요리</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>외국어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>헬스케어</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>예술</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>일상생활</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button\" onclick=\"window.location.href='listings-half-screen-map-list.html'\">검색</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Content -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h3 class=\"headline centered margin-top-75\">\r\n");
      out.write("\t\t\t\t\t인기 서비스\r\n");
      out.write("\t\t\t\t</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Categories Carousel -->\r\n");
      out.write("\t<div class=\"fullwidth-carousel-container margin-top-25\">\r\n");
      out.write("\t\t<div class=\"fullwidth-slick-carousel category-carousel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t<a href=\"listings-half-screen-map-grid-1.html\" class=\"category-box\" data-background-image=\"../img/art.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>예술</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>64 listings</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t<a href=\"listings-half-screen-map-grid-1.html\" class=\"category-box\" data-background-image=\"../img/language.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>외국어</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>67 listings</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t<a href=\"listings-half-screen-map-grid-1.html\" class=\"category-box\" data-background-image=\"../img/gym.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>헬스케어</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>27 listings</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t<a href=\"listings-half-screen-map-list.html\" class=\"category-box\" data-background-image=\"../img/business.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>비즈니스</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>22 listings</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Item -->\r\n");
      out.write("\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t<a href=\"listings-half-screen-map-list.html\" class=\"category-box\" data-background-image=\"../img/cooking.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>요리</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>130 listings</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"fw-carousel-item\">\r\n");
      out.write("\t\t\t\t<div class=\"category-box-container\">\r\n");
      out.write("\t\t\t\t\t<a href=\"listings-half-screen-map-grid-1.html\" class=\"category-box\" data-background-image=\"../img/clean.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"category-box-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>일상생활</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>64 listings</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"category-box-btn\">Browse</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Categories Carousel / End -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Fullwidth Section -->\r\n");
      out.write("\t<section style=\"display: none\" class=\"fullwidth margin-top-65 padding-top-75 padding-bottom-70\" data-background-color=\"#f8f8f8\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"display:none\" class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"headline centered margin-bottom-45\">\r\n");
      out.write("\t\t\t\t\t\tMost Visited Places\r\n");
      out.write("\t\t\t\t\t\t<span>Discover top-rated local businesses</span>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"simple-slick-carousel dots-nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-single-page.html\" class=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/listing-item-01.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-badge now-open\">Now Open</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tag\">Eat & Drink</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Tom's Restaurant <i class=\"verified-icon\"></i></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>964 School Street, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"3.5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(12 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-single-page.html\" class=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/listing-item-02.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-item-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Friday, August 10</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tag\">Events</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Sticky Band</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Bishop Avenue, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"5.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(23 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-single-page.html\" class=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/listing-item-03.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-item-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Starting from $59 per night</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tag\">Hotels</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Hotel Govendor</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>778 Country Street, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"2.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(17 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-single-page.html\" class=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/listing-item-04.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-badge now-open\">Now Open</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tag\">Eat & Drink</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Burger House <i class=\"verified-icon\"></i></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>2726 Shinn Street, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"5.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(31 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-single-page.html\" class=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/listing-item-05.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tag\">Other</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Airport</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>1512 Duncan Avenue, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"3.5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(46 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listings-single-page.html\" class=\"listing-item-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"listing-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/listing-item-06.jpg\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-badge now-closed\">Now Closed</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"listing-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tag\">Eat & Drink</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Think Coffee</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>215 Terry Lane, New York</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"like-icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"star-rating\" data-rating=\"4.5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"rating-counter\">(15 reviews)</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Listing Item / End -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Fullwidth Section / End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Info Section -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("\t\t\t\t<h2 class=\"headline centered margin-top-80\">\r\n");
      out.write("\t\t\t\t\t故 신영복 선생 「스승과 제자」\r\n");
      out.write("\t\t\t\t\t<span class=\"margin-top-25\">\"우리는 저마다 누군가의 제자이면서 동시에 누군가의 스승입니다. 배우고 가르치는 사제(師弟)의 연쇄(連鎖)를 확인하는 것이 곧 자기(自己)의 발견입니다.\"</span>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row icons-container\">\r\n");
      out.write("\t\t\t<!-- Stage -->\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-box-2 with-line\">\r\n");
      out.write("\t\t\t\t\t<i class=\"im im-icon-Map2\"></i>\r\n");
      out.write("\t\t\t\t\t<h3>Find Interesting Place</h3>\r\n");
      out.write("\t\t\t\t\t<p>Proin dapibus nisl ornare diam varius tempus. Aenean a quam luctus, finibus tellus ut, convallis eros sollicitudin turpis.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Stage -->\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-box-2 with-line\">\r\n");
      out.write("\t\t\t\t\t<i class=\"im im-icon-Mail-withAtSign\"></i>\r\n");
      out.write("\t\t\t\t\t<h3>Contact a Few Owners</h3>\r\n");
      out.write("\t\t\t\t\t<p>Maecenas pulvinar, risus in facilisis dignissim, quam nisi hendrerit nulla, id vestibulum metus nullam viverra porta purus.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Stage -->\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-box-2\">\r\n");
      out.write("\t\t\t\t\t<i class=\"im im-icon-Checked-User\"></i>\r\n");
      out.write("\t\t\t\t\t<h3>Make a Reservation</h3>\r\n");
      out.write("\t\t\t\t\t<p>Faucibus ante, in porttitor tellus blandit et. Phasellus tincidunt metus lectus sollicitudin feugiat pharetra consectetur.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Info Section / End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Recent Blog Posts -->\r\n");
      out.write("\t<section style=\"display:none\" class=\"fullwidth border-top margin-top-70 padding-top-75 padding-bottom-75\" data-background-color=\"#fff\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"headline centered margin-bottom-45\">\r\n");
      out.write("\t\t\t\t\t\tFrom The Blog\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- Blog Post Item -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<a href=\"pages-blog-post.html\" class=\"blog-compact-item-container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"blog-compact-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../img/blog-compact-post-01.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"blog-item-tag\">Tips</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"blog-compact-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"blog-post-tags\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>22 August 2019</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Hotels for All Budgets</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Sed sed tristique nibh iam porta volutpat finibus. Donec in aliquet urneget mattis lorem. Pellentesque pellentesque.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Blog post Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Blog Post Item -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<a href=\"pages-blog-post.html\" class=\"blog-compact-item-container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"blog-compact-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../img/blog-compact-post-02.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"blog-item-tag\">Tips</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"blog-compact-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"blog-post-tags\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>18 August 2019</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>The 50 Greatest Street Arts In London</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Sed sed tristique nibh iam porta volutpat finibus. Donec in aliquet urneget mattis lorem. Pellentesque pellentesque.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Blog post Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Blog Post Item -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<a href=\"pages-blog-post.html\" class=\"blog-compact-item-container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"blog-compact-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../img/blog-compact-post-03.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"blog-item-tag\">Tips</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"blog-compact-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"blog-post-tags\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>10 August 2019</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>The Best Cofee Shops In Sydney Neighborhoods</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Sed sed tristique nibh iam porta volutpat finibus. Donec in aliquet urneget mattis lorem. Pellentesque pellentesque.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Blog post Item / End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 centered-content\">\r\n");
      out.write("\t\t\t\t\t<a href=\"pages-blog.html\" class=\"button border margin-top-10\">View Blog</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Recent Blog Posts / End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<div id=\"footer\" class=\"sticky-footer\">\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-5 col-sm-6\">\r\n");
      out.write("\t\t\t\t<img class=\"footer-logo\" src=\"../img/logo.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<p>Morbi convallis bibendum urna ut viverra. Maecenas quis consequat libero, a feugiat eros. Nunc ut lacinia tortor morbi ultricies laoreet ullamcorper phasellus semper.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-6 \">\r\n");
      out.write("\t\t\t\t<h4>Helpful Links</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"footer-links\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Sign Up</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">My Account</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Add Listing</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Pricing</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"footer-links\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Our Partners</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">How It Works</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-3  col-sm-12\">\r\n");
      out.write("\t\t\t\t<h4>Contact Us</h4>\r\n");
      out.write("\t\t\t\t<div class=\"text-widget\">\r\n");
      out.write("\t\t\t\t\t<span>12345 Little Lonsdale St, Melbourne</span> <br>\r\n");
      out.write("\t\t\t\t\tPhone: <span>(123) 123-456 </span><br>\r\n");
      out.write("\t\t\t\t\tE-Mail:<span> <a href=\"#\">office@example.com</a> </span><br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"social-icons margin-top-20\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"facebook\" href=\"#\"><i class=\"icon-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"twitter\" href=\"#\"><i class=\"icon-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"gplus\" href=\"#\"><i class=\"icon-gplus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"vimeo\" href=\"#\"><i class=\"icon-vimeo\"></i></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Copyright -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div class=\"copyrights\">© 2019 Listeo. All Rights Reserved.</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Footer / End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Back To Top Button -->\r\n");
      out.write("<div id=\"backtotop\"><a href=\"#\"></a></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Wrapper / End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-2.2.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/mmenu.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/chosen.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/slick.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/rangeslider.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/magnific-popup.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/waypoints.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/counterup.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/tooltips.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/custom.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/apis.js\"></script>\r\n");
      out.write("<script src=\"../js/redirect.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Google Autocomplete -->\r\n");
      out.write("<script>\r\n");
      out.write("  function initAutocomplete() {\r\n");
      out.write("    var input = document.getElementById('autocomplete-input');\r\n");
      out.write("    var autocomplete = new google.maps.places.Autocomplete(input);\r\n");
      out.write("\r\n");
      out.write("    autocomplete.addListener('place_changed', function() {\r\n");
      out.write("      var place = autocomplete.getPlace();\r\n");
      out.write("      if (!place.geometry) {\r\n");
      out.write("        window.alert(\"No details available for input: '\" + place.name + \"'\");\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\tif ($('.main-search-input-item')[0]) {\r\n");
      out.write("\t    setTimeout(function(){ \r\n");
      out.write("\t        $(\".pac-container\").prependTo(\"#autocomplete-container\");\r\n");
      out.write("\t    }, 300);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?libraries=places&callback=initAutocomplete\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Style Switcher -->\r\n");
      out.write("<script src=\"../js/switcher.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"style-switcher\">\r\n");
      out.write("\t<h2>Color Switcher <a href=\"#\"><i class=\"sl sl-icon-settings\"></i></a></h2>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<ul class=\"colors\" id=\"color1\">\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"main\" title=\"Main\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"blue\" title=\"Blue\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"green\" title=\"Green\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"orange\" title=\"Orange\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"navy\" title=\"Navy\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"yellow\" title=\"Yellow\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"peach\" title=\"Peach\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"beige\" title=\"Beige\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"purple\" title=\"Purple\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"celadon\" title=\"Celadon\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"red\" title=\"Red\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"brown\" title=\"Brown\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"cherry\" title=\"Cherry\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"cyan\" title=\"Cyan\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"gray\" title=\"Gray\"></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"olive\" title=\"Olive\"></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Style Switcher / End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/main.jsp(49,23) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("hasRole(ROLE_CUSTOMER)");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("                           <div class=\"user-name\"><span><img src=\"\" alt=\"\"></span> memberId + 님, 안녕하세요!</div>\r\n");
        out.write("                           <ul>\r\n");
        out.write("                                <li><a onclick=\"viewCustomerMyPage();\"><i class=\"sl sl-icon-settings\"></i> 마이페이지</a></li>\r\n");
        out.write("                               <li><a onclick=\"viewBookmark();\"><i class=\"fa fa-calendar-check-o\"></i> 나의 수강 관리</a></li>\r\n");
        out.write("                               <li><a action=\"/logout\"><i class=\"sl sl-icon-power\"></i> 로그아웃</a></li>\r\n");
        out.write("                            </ul>\r\n");
        out.write("                       ");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/main.jsp(57,23) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("hasRole(ROLE_PROVIDER)");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("                           <div class=\"user-name\"><span><img src=\"\" alt=\"\"></span> memberId + 님, 안녕하세요!</div>\r\n");
        out.write("                           <ul>\r\n");
        out.write("                                <li><a onclick=\"viewProviderMyPage();\"><i class=\"sl sl-icon-settings\"></i> 마이페이지</a></li>\r\n");
        out.write("                               <li><a onclick=\"viewMyListing();\"><i class=\"fa fa-calendar-check-o\"></i> 나의 수업 관리</a></li>\r\n");
        out.write("                               <li><a action=\"/logout\"><i class=\"sl sl-icon-power\"></i> 로그아웃</a></li>\r\n");
        out.write("                            </ul>\r\n");
        out.write("                            </div><a onclick=\"viewAddListing();\" class=\"button border with-icon\">수업 개설하기<i class=\"sl sl-icon-plus\"></i></a></div>\r\n");
        out.write("                       ");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/main.jsp(66,24) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("                           <a onclick=\"viewMemberLogin();\" class=\"sign-in\">로그인</a>\r\n");
        out.write("                           <a onclick=\"viewMemberRegister();\" class=\"sign-in\">회원가입</a>\r\n");
        out.write("                        ");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }
}
